enabled: true

hmacToken: "{{ .Parameters.prow.hmacToken }}"
oauthToken: "{{ .Parameters.pipelineUser.token }}"
user: "{{ .Parameters.pipelineUser.username }}"
tillerNamespace: ""

deck:
  replicaCount: 1
  datadog:
    enabled: false

buildnum:
  enabled: false

tillerNamespace: ""

deck:
  replicaCount: 1
  datadog:
    enabled: false
  args:
    - --spyglass
    - --hook-url=http://hook/plugin-help
    - --tide-url=http://tide

pipelinerunner:
  enabled: true
  args:
  - controller
  - pipelinerunner
  - --use-meta-pipeline=false
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    GIT_AUTHOR_NAME: "{{ .Parameters.pipelineUser.username }}"
    GIT_AUTHOR_EMAIL: "{{ .Parameters.pipelineUser.email }}"
  datadog:
    enabled: false

buildnum:
  enabled: false
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  datadog:
    enabled: true

crier:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  datadog:
    enabled: false

branchprotector:
  enabled: false
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  datadog:
    enabled: false

hook:
  replicaCount: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  datadog:
    enabled: false

horologium:
  datadog:
    enabled: false

plank:
  datadog:
    enabled: false

build:
  datadog:
    enabled: false

pipeline:
  datadog:
    enabled: false

sinker:
  replicaCount: 1
