enabled: true

hmacToken: "{{ .Parameters.prow.hmacToken }}"
oauthToken: "{{ .Parameters.pipelineUser.token }}"
user: "{{ .Parameters.pipelineUser.username }}"

buildnum:
  enabled: false

tillerNamespace: ""

deck:
  replicaCount: 1
  datadog:
    enabled: false
  args:
    - --spyglass
    - --hook-url=http://hook/plugin-help
    - --tide-url=http://tide

pipelinerunner:
  enabled: "true"
  args:
  - controller
  - pipelinerunner
  - --use-meta-pipeline=false
tillerNamespace: ""

sinker:
  replicaCount: 1
